### ISSUE TITLE
SSL Wrong Version Number

### ISSUE THREAD

**Issue by lovesegfault** [jonringer/server-configuration#14]
For some reason `nixpkgs-review` on this host will break with some SSL issue quite often. I'm not sure whether we're missing some config that's causing these issues. Seems cert-related?
```
[bemeurer@nixos:~/src/nixpkgs]$ nix-shell -p nixpkgs-review

[nix-shell:~/src/nixpkgs]$ nixpkgs-review pr 140514
$ git worktree prune
Traceback (most recent call last):
  File "/nix/store/dqxic3j7csd4ywn94n4smmnz55p039g3-python3-3.9.6/lib/python3.9/urllib/request.py", line 1346, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/nix/store/dqxic3j7csd4ywn94n4smmnz55p039g3-python3-3.9.6/lib/python3.9/http/client.py", line 1257, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/nix/store/dqxic3j7csd4ywn94n4smmnz55p039g3-python3-3.9.6/lib/python3.9/http/client.py", line 1303, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/nix/store/dqxic3j7csd4ywn94n4smmnz55p039g3-python3-3.9.6/lib/python3.9/http/client.py", line 1252, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/nix/store/dqxic3j7csd4ywn94n4smmnz55p039g3-python3-3.9.6/lib/python3.9/http/client.py", line 1012, in _send_output
    self.send(msg)
  File "/nix/store/dqxic3j7csd4ywn94n4smmnz55p039g3-python3-3.9.6/lib/python3.9/http/client.py", line 952, in send
    self.connect()
  File "/nix/store/dqxic3j7csd4ywn94n4smmnz55p039g3-python3-3.9.6/lib/python3.9/http/client.py", line 1426, in connect
    self.sock = self._context.wrap_socket(self.sock,
  File "/nix/store/dqxic3j7csd4ywn94n4smmnz55p039g3-python3-3.9.6/lib/python3.9/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/nix/store/dqxic3j7csd4ywn94n4smmnz55p039g3-python3-3.9.6/lib/python3.9/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/nix/store/dqxic3j7csd4ywn94n4smmnz55p039g3-python3-3.9.6/lib/python3.9/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1129)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/nix/store/w1k5cnqqf6bsqxd06sh00bprz7k0vz2a-nixpkgs-review-2.6.2/bin/.nixpkgs-review-wrapped", line 9, in <module>
    sys.exit(main())
  File "/nix/store/w1k5cnqqf6bsqxd06sh00bprz7k0vz2a-nixpkgs-review-2.6.2/lib/python3.9/site-packages/nixpkgs_review/__init__.py", line 10, in main
    cli.main(command, args)
  File "/nix/store/w1k5cnqqf6bsqxd06sh00bprz7k0vz2a-nixpkgs-review-2.6.2/lib/python3.9/site-packages/nixpkgs_review/cli/__init__.py", line 262, in main
    return cast(str, args.func(args))
  File "/nix/store/w1k5cnqqf6bsqxd06sh00bprz7k0vz2a-nixpkgs-review-2.6.2/lib/python3.9/site-packages/nixpkgs_review/cli/pr.py", line 65, in pr_command
    contexts.append((pr, builddir.path, review.build_pr(pr)))
  File "/nix/store/w1k5cnqqf6bsqxd06sh00bprz7k0vz2a-nixpkgs-review-2.6.2/lib/python3.9/site-packages/nixpkgs_review/review.py", line 201, in build_pr
    packages_per_system = self.github_client.get_borg_eval_gist(pr)
  File "/nix/store/w1k5cnqqf6bsqxd06sh00bprz7k0vz2a-nixpkgs-review-2.6.2/lib/python3.9/site-packages/nixpkgs_review/github.py", line 86, in get_borg_eval_gist
    for line in urllib.request.urlopen(raw_gist_url):
  File "/nix/store/dqxic3j7csd4ywn94n4smmnz55p039g3-python3-3.9.6/lib/python3.9/urllib/request.py", line 214, in urlopen
    return opener.open(url, data, timeout)
  File "/nix/store/dqxic3j7csd4ywn94n4smmnz55p039g3-python3-3.9.6/lib/python3.9/urllib/request.py", line 517, in open
    response = self._open(req, data)
  File "/nix/store/dqxic3j7csd4ywn94n4smmnz55p039g3-python3-3.9.6/lib/python3.9/urllib/request.py", line 534, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/nix/store/dqxic3j7csd4ywn94n4smmnz55p039g3-python3-3.9.6/lib/python3.9/urllib/request.py", line 494, in _call_chain
    result = func(*args)
  File "/nix/store/dqxic3j7csd4ywn94n4smmnz55p039g3-python3-3.9.6/lib/python3.9/urllib/request.py", line 1389, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "/nix/store/dqxic3j7csd4ywn94n4smmnz55p039g3-python3-3.9.6/lib/python3.9/urllib/request.py", line 1349, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1129)>
```

**Comment by jonringer** [comment]
I do `--eval local` and it seems to be fine


The issue come from trying to pull the gist. And I don't know why this issue is persisting.

**Comment by Artturin** [comment]
haven't had this happen this year

**Comment by lovesegfault** [comment]
Haven't had this happen in forever, closing.
